apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: your-app
  template:
    metadata:
      labels:
        app: your-app
    spec:
      containers:
        - name: your-app
          image: 471112778737.dkr.ecr.ap-south-1.amazonaws.com/my_repository/my_repository:latest
          ports:
            - containerPort: 80
