name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build . -t my_repository/valaxy-technologies:latest
      working-directory: ./

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 471112778737.dkr.ecr.ap-south-1.amazonaws.com

    - name: Tag Docker image
      run: docker tag my_repository/valaxy-technologies:latest 471112778737.dkr.ecr.ap-south-1.amazonaws.com/valaxy-technologies:latest
    
    - name: Push Docker image to Amazon ECR
      run: docker push 471112778737.dkr.ecr.ap-south-1.amazonaws.com/valaxy-technologies:latest
