name: Update Deployment with Latest Image

on:
  push:
    branches:
      - main

jobs:
  build_and_update_deployment:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      env:
        TIMESTAMP: $(date +%Y%m%d%H%M%S) # Generate timestamp
      run: |
        docker build . -t ecr_user/my_repository:latest
        echo "::set-output name=image_tag::ecr_user/my_repository:${{ env.TIMESTAMP }}"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 471112778737.dkr.ecr.ap-south-1.amazonaws.com

    - name: Tag Docker image
      env:
        TIMESTAMP: $(date +%Y%m%d%H%M%S) # Use the same timestamp for tagging
      run: docker tag ecr_user/my_repository:latest 471112778737.dkr.ecr.ap-south-1.amazonaws.com/my_repository:${{ env.TIMESTAMP }}

    - name: Replace timestamp in deployment file
      run: sed -i "s|471112778737\.dkr\.ecr\.ap-south-1\.amazonaws\.com/my_repository:latest|471112778737\.dkr\.ecr\.ap-south-1\.amazonaws\.com/my_repository:${{ steps.build_docker_image.outputs.timestamp }}|" deployment.yaml
    
    - name: Push Docker image to Amazon ECR
      env:
        TIMESTAMP: $(date +%Y%m%d%H%M%S) # Use the same timestamp for tagging
      run: docker push 471112778737.dkr.ecr.ap-south-1.amazonaws.com/my_repository:${{ env.TIMESTAMP }}"
      
    - name: Commit changes
      run: |
        git config --local user.email "deepakramanan10@gmail.com"
        git config --local user.name "Deepak Ramanan"
        git add deployment.yaml
        git commit -m "Update deployment with latest image tag"
        git push
      

     
